package aoc2025.day7;

import org.junit.jupiter.api.Test;

import java.util.stream.Stream;

class BeamSplitterTest {
    @Test
    void testSPlits() {
        String lines = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""";

        BeamSplitter bs = new  BeamSplitter(Stream.of(lines.split("\n")).toList());

    }

}